// ADD YOUR OWN KEYS AND RENAME THIS FILE TO keys.js
const TWITTER_TOKENS = {
  TWITTER_CONSUMER_KEY: "0Y42EKLLt3IwyYALd8gsR01xP",
  TWITTER_CONSUMER_SECRET: "fJkC4jOcTjT2OhJiNzQiiCiEM2rONOch9liXIyMZ7KRrVJ5MYF",
  TWITTER_ACCESS_TOKEN: "SOME ACCESS TOKEN",
  TWITTER_TOKEN_SECRET: "SOME TOKEN SECRET",
  TWITTER_BEARER_TOKEN: 'AAAAAAAAAAAAAAAAAAAAAHXiiwEAAAAAw3pWxrfIdVptvMeeI0gpP6sywoY%3DDrk6znVKJL6PxYjrpqv45AznByPI9X9gy6BUx21dhdNFy3TPkU'

};

const DB_USER = "admin";
const DB_PASSWORD = "admin";
const DOMAIN = 'localhost';
const PORT = 3333;
const DB = 'tickets'
const MONGODB = {
  MONGODB_URI: `mongodb://${DB_USER}:${DB_PASSWORD}@ds:${DOMAIN}:${PORT}/${DB}`
};

const SESSION = {
  COOKIE_KEY: "thisappisawesome"
};

const KEYS = {
  ...TWITTER_TOKENS,
  ...MONGODB,
  ...SESSION
};

module.exports = KEYS;
